const K='naneice-v3';
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const today=()=>new Date().toISOString().slice(0,10);
const fmt=d=>{try{return new Date(d).toLocaleDateString('ar-EG',{year:'numeric',month:'short',day:'numeric'})}catch{return d||'\u2014'}};
const money=n=>Number(n||0).toLocaleString('ar-EG');
const load=()=>{try{return JSON.parse(localStorage.getItem(K))||null}catch{return null}};
const save=()=>localStorage.setItem(K,JSON.stringify(data));
let data=load()||{pin:'1234',teacherName:'\u062f. \u0646\u0627\u0646\u064a\u0633 \u0627\u0644\u0634\u064a\u0645\u064a',students:[],sessions:[],groups:[],homework:[],finance:[]};
if(!data.groups)data.groups=[];
if(!data.homework)data.homework=[];
if(!data.finance)data.finance=[];
let auth=sessionStorage.getItem('na')==='1', page='home', modal=null;
const stats=()=>{const t=data.sessions.filter(s=>s.date===today());const inc=data.finance.filter(f=>f.type==='income').reduce((a,f)=>a+Number(f.amount),0);const exp=data.finance.filter(f=>f.type==='expense').reduce((a,f)=>a+Number(f.amount),0);return{total:data.students.length,active:data.students.filter(s=>s.remainingSessions>0).length,expired:data.students.filter(s=>s.remainingSessions<=0).length,low:data.students.filter(s=>s.remainingSessions>0&&s.remainingSessions<=3).length,today:t.length,done:t.filter(s=>s.status==='completed').length,up:t.filter(s=>s.status==='scheduled').length,groups:data.groups.length,hwOpen:data.homework.filter(h=>h.status!=='done').length,income:inc,expense:exp,net:inc-exp}};
function seed(){if(data.students.length)return;const a={id:uid(),name:'\u0645\u0631\u064a\u0645 \u0623\u062d\u0645\u062f',subject:'\u0639\u0644\u0648\u0645',level:'\u0627\u0644\u0635\u0641 \u0627\u0644\u0633\u0627\u0628\u0639',totalSessions:12,remainingSessions:5,end:today()};const b={id:uid(),name:'\u064a\u0648\u0633\u0641 \u0645\u062d\u0645\u0648\u062f',subject:'\u0639\u0644\u0648\u0645',level:'\u0627\u0644\u0635\u0641 \u0627\u0644\u0633\u0627\u062f\u0633',totalSessions:8,remainingSessions:2,end:today()};const c={id:uid(),name:'\u0644\u064a\u0646\u0627 \u0633\u0627\u0645\u064a',subject:'\u0639\u0644\u0648\u0645',level:'\u0627\u0644\u0635\u0641 \u0627\u0644\u0633\u0627\u0628\u0639',totalSessions:10,remainingSessions:0,end:today()};data.students=[a,b,c];data.sessions=[{id:uid(),studentId:a.id,studentName:a.name,date:today(),time:'16:00',dur:60,status:'scheduled'},{id:uid(),studentId:b.id,studentName:b.name,date:today(),time:'17:30',dur:60,status:'scheduled'}];data.groups=[{id:uid(),name:'\u0639\u0644\u0648\u0645 7\u0623',subject:'\u0639\u0644\u0648\u0645',capacity:6,memberIds:[a.id],active:true}];data.homework=[{id:uid(),studentId:a.id,studentName:a.name,title:'\u0648\u0631\u0642\u0629 \u0627\u0644\u062e\u0644\u064a\u0629',due:today(),status:'pending'}];data.finance=[{id:uid(),type:'income',amount:500,note:'\u0627\u0634\u062a\u0631\u0627\u0643 \u0645\u0631\u064a\u0645',date:today()},{id:uid(),type:'expense',amount:80,note:'\u0623\u0648\u0631\u0627\u0642 \u0639\u0645\u0644',date:today()}];save();render()}
function go(p){page=p;modal=null;render()}
function login(e){e.preventDefault();if(document.getElementById('pin').value.trim()===data.pin){auth=true;sessionStorage.setItem('na','1');render()}else document.getElementById('err').textContent='\u0631\u0645\u0632 \u0627\u0644\u062f\u062e\u0648\u0644 \u063a\u064a\u0631 \u0635\u062d\u064a\u062d';return false}
function openSt(id){modal={t:'st',id:id||null};render()}
function openSe(){modal={t:'se'};render()}
function openFi(id){modal={t:'fi',id};render()}
function openGr(id){modal={t:'gr',id:id||null};render()}
function openHw(){modal={t:'hw'};render()}
function openFn(){modal={t:'fn'};render()}
function delSt(id){if(confirm('\u062d\u0630\u0641 \u0627\u0644\u0637\u0627\u0644\u0628\u061f')){data.students=data.students.filter(s=>s.id!==id);data.sessions=data.sessions.filter(s=>s.studentId!==id);data.homework=data.homework.filter(h=>h.studentId!==id);data.groups=data.groups.map(g=>({...g,memberIds:(g.memberIds||[]).filter(m=>m!==id)}));save();render()}}
function delSe(id){data.sessions=data.sessions.filter(s=>s.id!==id);save();render()}
function delGr(id){if(confirm('\u062d\u0630\u0641 \u0627\u0644\u0645\u062c\u0645\u0648\u0639\u0629\u061f')){data.groups=data.groups.filter(g=>g.id!==id);save();render()}}
function delHw(id){data.homework=data.homework.filter(h=>h.id!==id);save();render()}
function delFn(id){data.finance=data.finance.filter(f=>f.id!==id);save();render()}
function togGr(id){data.groups=data.groups.map(g=>g.id===id?{...g,active:g.active===false}:g);save();render()}
function doneHw(id){data.homework=data.homework.map(h=>h.id===id?{...h,status:'done'}:h);save();render()}
function start(id){data.sessions=data.sessions.map(s=>s.id===id?{...s,status:'active'}:s);save();render()}
function renew(id){data.students=data.students.map(s=>s.id===id?{...s,remainingSessions:s.remainingSessions+8,totalSessions:s.totalSessions+8}:s);save();render()}
function sv(){data.teacherName=document.getElementById('tn').value.trim()||data.teacherName;data.pin=document.getElementById('tp').value.trim()||data.pin;save();alert('\u062a\u0645 \u0627\u0644\u062d\u0641\u0638');render()}
function exp(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='naneice-backup.json';a.click()}
function imp(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);if(!data.groups)data.groups=[];if(!data.homework)data.homework=[];if(!data.finance)data.finance=[];save();alert('\u062a\u0645\u062a \u0627\u0644\u0627\u0633\u062a\u0639\u0627\u062f\u0629');render()}catch{alert('\u0645\u0644\u0641 \u063a\u064a\u0631 \u0635\u0627\u0644\u062d')}};r.readAsText(f)}
function saveSt(e){e.preventDefault();const f=new FormData(e.target);const p={name:f.get('name').toString().trim(),subject:f.get('subject').toString().trim(),level:f.get('level').toString().trim(),totalSessions:+f.get('total')||0,remainingSessions:+f.get('rem')||0,end:f.get('end').toString()||today()};if(modal.id)data.students=data.students.map(s=>s.id===modal.id?{...s,...p}:s);else data.students.unshift({id:uid(),...p});save();modal=null;render();return false}
function saveSe(e){e.preventDefault();const f=new FormData(e.target);const sid=f.get('sid').toString();const st=data.students.find(s=>s.id===sid);if(!st)return false;data.sessions.push({id:uid(),studentId:sid,studentName:st.name,date:today(),time:f.get('time').toString(),dur:+f.get('dur')||60,status:'scheduled'});save();modal=null;render();return false}
function fin(e){e.preventDefault();const f=new FormData(e.target);const id=modal.id;const att=f.get('att').toString();const se=data.sessions.find(s=>s.id===id);data.sessions=data.sessions.map(s=>s.id===id?{...s,status:'completed',attendance:att,homework:f.get('hw').toString()}:s);if(se&&(att==='Present'||att==='Late'))data.students=data.students.map(st=>st.id===se.studentId?{...st,remainingSessions:Math.max(0,st.remainingSessions-1)}:st);save();modal=null;render();return false}
function saveGr(e){e.preventDefault();const f=new FormData(e.target);const members=Array.from(e.target.members.selectedOptions).map(o=>o.value);const cap=+f.get('capacity')||6;if(members.length>cap){alert('\u0639\u062f\u062f \u0627\u0644\u0623\u0639\u0636\u0627\u0621 \u0623\u0643\u0628\u0631 \u0645\u0646 \u0627\u0644\u0633\u0639\u0629');return false}const p={name:f.get('name').toString().trim(),subject:f.get('subject').toString().trim(),capacity:cap,memberIds:members,active:true};if(modal.id){const old=data.groups.find(g=>g.id===modal.id);data.groups=data.groups.map(g=>g.id===modal.id?{...g,...p,active:old?old.active!==false:true}:g)}else data.groups.unshift({id:uid(),...p});save();modal=null;render();return false}
function saveHw(e){e.preventDefault();const f=new FormData(e.target);const sid=f.get('sid').toString();const st=data.students.find(s=>s.id===sid);if(!st)return false;data.homework.unshift({id:uid(),studentId:sid,studentName:st.name,title:f.get('title').toString().trim(),due:f.get('due').toString(),status:'pending'});save();modal=null;render();return false}
function saveFn(e){e.preventDefault();const f=new FormData(e.target);data.finance.push({id:uid(),type:f.get('type').toString(),amount:+f.get('amount')||0,note:f.get('note').toString().trim(),date:f.get('date').toString()||today()});save();modal=null;render();return false}
